### ISSUE TITLE
how to initiate

### ISSUE THREAD

**Issue by magickarle** [jojje/vai-docker#1]
Noob question.
Do i need to copy this git or can i use a compose docker file?
I've read the readme but I feel there's something i need to do before the make login.

Thanks.

**Comment by jojje** [comment]
You just clone the repository and run "docker build". The only thing added to the container from this repo is the docker-init script. The only purpose that script serves is to make getting the topaz license key easy.

However the repository is laid out so as to make building the docker-file with the required topaz license key as easy as possible, so I would recommend you just clone the repository, build the container image and get the license key using it. Once that's done, you can run the image however and from wherever you like.

If you don't have "make" on your system, then install it via your package manager. E.g. for Ubuntu or Debian, run `apt-get install make`. Then just follow the readme steps.

1. `make build` creates the docker image for you.
2. `make login` guides you through getting the topaz license key (named `auth.tpz`)

Once you have those two elements (image + license), you can run the container however you like.

Note that I don't bake the license into the image, but expect it to be volume mounted in the container's `/models` directory. That's why there's an empty `models` directory in this repo, The "make login" command gets the license key and stores it in the project's models directory. Once you have the license key, you can copy it to wherever you prefer, and run the container from wherever you like; in your case with compose from some directory. 

There is a make target named `test`, which will run the topaz ffmpeg with a test clip. It's intended to serve as both an example of how to run the container, but also to verify that your container, VAI, your license  and your host machine all work together as expected.

If you just want to preview the commands required, and then script or "compose" the commands yourself, you can run the make targets in a "dry-run" (simulated mode) using the `-n` flag for `make`.

```
make -n build
make -n login
make -n test
```

Hope this answers your question.

**Comment by jojje** [comment]
Closing due to 5 months of inactivity.
